# These are all the cops that are disabled in the default configuration.

Style/InlineComment:
  Description: "Avoid inline comments."
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Description: "Avoid chaining a method call on a do...end block."
  Enabled: false

Style/SymbolArray:
  Description: "Use %i or %I for arrays of symbols."
  Enabled: false

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Description: "Keep blank lines around access modifiers."
  Enabled: false

Style/EmptyLiteral:
  Description: "Prefer literals to Array.new/Hash.new/String.new."
  Enabled: false

Style/ClassAndModuleChildren:
  Description: "Checks style of children classes and modules."
  Enabled: false

Style/ClassLength:
  Description: "Avoid classes longer than 100 lines of code."
  Enabled: false

Style/MethodLength:
  Description: "Avoid methods longer than 10 lines of code."
  Enabled: false

Style/ParameterLists:
  Description: "Avoid parameter lists longer than three or four parameters."
  Enabled: false

